config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "organisations#index"

  devise_for :users

  resources :search, only: [:index]

  resources :organisations, except: [:show] do
    resources :software_instances, shallow: true, path: :software
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :users
  has_many :software_instances

  validates :name, :tag, presence: true
  validates(
    :tag,
    uniqueness: true,
    format: {
      with: /\A[a-zA-Z0-9][\w\-]*[a-zA-Z0-9]\z/,
      message: 'must not have spaces but can be split with hyphens or underscores'
    }
  )

  def to_param
    tag
  end
end

app/models/software_instance.rb
class SoftwareInstance < ApplicationRecord
  include PgSearch::Model
  multisearchable against: %i[
    product
    provider
    name
    description
    packages
  ]

  belongs_to :organisation

  # Target validation. At this stage supplied data is incomplete
  # TODO re-enable this validation
  # validates :organisation_group, :team, :product, :provider, :description, :status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :validatable, :trackable

  belongs_to :organisation, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :authenticate_user!, except: %i[index]

  # GET /organisations
  def index
    authorize @organisations = Organisation.left_joins(:software_instances)
                                           .select("organisations.*, COUNT(software_instances.id) AS software_instance_count")
                                           .group("organisations.id")
  end

  # GET /organisations/new
  def new
    authorize @organisation = Organisation.new
  end

  # POST /organisations
  def create
    authorize @organisation = Organisation.new(organisation_params)

    if organisation.save
      redirect_to organisation_software_path, notice: "Organisation was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /organisations/1/edit
  def edit
    organisation
  end

  # PATCH/PUT /organisations/1
  def update
    if organisation.update(organisation_params)
      redirect_to organisation_software_path, notice: "Organisation was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /organisations/1
  def destroy
    organisation.destroy!
    redirect_to organisations_url, notice: "Organisation was successfully destroyed."
  end

private

  def organisation_software_path
    organisation_software_instances_path(organisation)
  end

  # Use callbacks to share common setup or constraints between actions.
  def organisation
    @organisation ||= authorize Organisation.find_by(tag: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def organisation_params
    params.require(:organisation).permit(:name, :tag)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    result = PgSearch.multisearch(params[:q]).limit(10)
    @software_instances = result.map(&:searchable)
  end
end

app/controllers/software_instances_controller.rb
class SoftwareInstancesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :organisation

  def index
    authorize @software_instances = organisation.software_instances
  end

  def show
    software_instance
  end

  def new
    authorize @software_instance = organisation.software_instances.build
  end

  def create
    authorize @software_instance = organisation.software_instances.build(software_instance_params)

    if software_instance.save
      redirect_to software_instance, notice: "Software instance was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    software_instance
  end

  def update
    if software_instance.update(software_instance_params)
      redirect_to software_instance, notice: "Software instance was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    software_instance.destroy!
    redirect_to organisation_software_instances_path(organisation), notice: "Software instance was successfully destroyed."
  end

private

  def software_instance
    @software_instance ||= authorize SoftwareInstance.find(params[:id])
  end

  def organisation
    @organisation ||= if params[:organisation_id].present?
                        Organisation.find_by!(tag: params[:organisation_id])
                      else
                        software_instance.organisation
                      end
  end

  # Only allow a list of trusted parameters through.
  def software_instance_params
    params.require(:software_instance).permit(:name, :organisation_id, :organisation_group, :team, :owner, :product, :provider, :provider_contact, :version, :description, :status, :internal, :license, :quantity_purchased, :quantity_used)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(prefix)
    return prefix if current_page?(root_url)

    [prefix, page_title_suffix].flatten.map(&:titleize).join(' - ')
  end

  def page_title_suffix
    return "Organisation #{params[:organisation_id]} Software" if controller_name == 'software_instances' && action_name == 'index'
    return controller_name if action_name == 'index'
    return [controller_name, action_name] if params[:id].blank?

    [controller_name, "#{action_name} #{params[:id]}"]
  end
end

app/helpers/govuk_helper.rb
module GovukHelper
  def govuk_browser_title
    return controller_name.titleize if action_name == 'index'
    return "#{controller_name.singularize} #{params[:id]}".titleize if action_name == 'show'

    "#{action_name} #{controller_name.singularize} #{params[:id]}".titleize
  end

  def govuk_link_to(name = nil, options = nil, html_options = {}, &block)
    html_options[:class] = [html_options[:class], 'govuk-link'].flatten.compact
    link_to(name, options, html_options, &block)
  end
end

app/views/layouts/_search.html.erb
<%= form_tag(search_index_path, method: :get) do %>
  <%= text_field_tag :q, params[:q], class: "govuk-input govuk-input--width-20" %>
  <%= submit_tag 'Search', class: "govuk-button" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="govuk-template ">
  <head>
    <meta charset="utf-8">
    <title><%= page_title('Data Software Catalogue') %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <meta name="theme-color" content="#0b0c0c">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" sizes="16x16 32x32 48x48" href="/assets/images/favicon.ico" type="image/x-icon">
    <link rel="mask-icon" href="/assets/images/govuk-mask-icon.svg" color="#0b0c0c">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/images/govuk-apple-touch-icon-180x180.png">
    <link rel="apple-touch-icon" sizes="167x167" href="/assets/images/govuk-apple-touch-icon-167x167.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/assets/images/govuk-apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" href="/assets/images/govuk-apple-touch-icon.png">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "govuk" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="govuk-template__body">
    <script>
      document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');
    </script>
    <%= render 'layouts/header' %>
    <div class="govuk-width-container ">
      <main class="govuk-main-wrapper " id="main-content" role="main">
        <div class="govuk-grid-row">
          <div class="govuk-grid-column-two-thirds">
            <% if user_signed_in? %>
              <%= govuk_link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete } %>
            <% else %>
              <%= govuk_link_to "Log in", new_user_session_path %>
            <% end %>
            <%= content_tag(:p, notice, class: 'notice', style: "color: green") if notice.present? %>
            <%= content_tag(:p, alert, class: 'alert', style: "color: red") if alert.present? %>
            <%= render('layouts/search') if action_name == 'index' %>
            <%= yield %>
          </div>
        </div>
      </main>
    </div>
    <%= render "layouts/footer" %>
    <script>
      window.GOVUKFrontend.initAll()
    </script>
  </body>
</html>

app/views/organisations/_form.html.erb
<%= form_with(model: organisation) do |form| %>
  <% if organisation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(organisation.errors.count, "error") %> prohibited this organisation from being saved:</h2>

      <ul>
        <% organisation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="govuk-form-group">
    <%= form.label :name, style: "display: block", class: "govuk-label" %>
    <%= form.text_field :name, class: "govuk-input" %>
  </div>

  <% unless organisation.persisted? %>
    <div class="govuk-form-group">
      <%= form.label :tag, style: "display: block", class: "govuk-label" %>
      <%= form.text_field :tag, class: "govuk-input" %>
    </div>
  <% end %>

  <div>
    <%= form.submit class: "govuk-button", data: { module: "govuk-button" } %>
  </div>
<% end %>

app/views/organisations/_organisation.html.erb
<div id="<%= dom_id organisation %>">
  <p>
    <strong>Name:</strong>
    <%= organisation.name %>
  </p>

</div>

app/views/organisations/edit.html.erb
<h1 class="govuk-heading-l">Editing organisation</h1>

<%= render "form", organisation: @organisation %>

<br>

<div>
  <%= govuk_link_to "Show this organisation", organisation_software_instances_path(@organisation) %> |
  <%= govuk_link_to "Back to organisations", root_path %>
</div>

app/views/organisations/index.html.erb
<table id="organisations" class="govuk-table">
  <caption class="govuk-table__caption govuk-table__caption--m">Organisations</caption>
  <thead class="govuk-table__head">
    <tr class="govuk-table__row">
      <th scope="col" class="govuk-table__header">Name</th>
      <th scope="col" class="govuk-table__header">Software instances</th>
    </tr>
  </thead>
  <tbody class="govuk-table__body">
    <% @organisations.each do |organisation| %>
      <tr class="govuk-table__row">
        <th scope="row" class="govuk-table__header">
          <%= govuk_link_to organisation.name, organisation_software_instances_path(organisation) %>
        </th>
        <td class="govuk-table__cell">
          <%= organisation.software_instance_count %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= govuk_link_to("New organisation", new_organisation_path) if policy(:organisation).new? %>

app/views/organisations/new.html.erb
<h1 class="govuk-heading-l">New organisation</h1>

<%= render "form", organisation: @organisation %>

<br>

<div>
  <%= govuk_link_to "Back to organisations", organisations_path %>
</div>

app/views/search/index.html.erb
<h1>Result for search: <%= params[:q] %></h1>

<h2>Software</h2>

<% if @software_instances.present? %>
  <table class="govuk-table" id="software_instances">
    <thead class="govuk-table__head">
      <tr class="govuk-table__row"">
        <th class="govuk-table__header">Name</th>
        <th class="govuk-table__header">Organisation</th>
        <th class="govuk-table__header">Product</th>
        <th class="govuk-table__header">Packages</th>
        <th class="govuk-table__header">Provider</th>
        <th class="govuk-table__header">Status</th>
        <th class="govuk-table__header"></th>
      </tr>
    </thead>
    <tbody class="govuk-table__body">
      <% @software_instances.each do |software_instance| %>
        <%= render software_instance %>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Software not found for this search</p>
<% end %>

app/views/software_instances/_form.html.erb
<%= simple_form_for(software_instance) do |form| %>
  <%= form.input :name %>
  <%= form.association :organisation, wrapper: :govuk_select %>
  <%= form.input :organisation_group %>
  <%= form.input :team %>
  <%= form.input :owner %>
  <%= form.input :product %>
  <%= form.input :provider %>
  <%= form.input :provider_contact %>
  <%= form.input :version %>
  <%= form.input :description, wrapper: :textarea %>
  <%= form.input :status %>
  <%= form.input :internal, wrapper: :boolean_input %>
  <%= form.input :license %>
  <%= form.input :quantity_purchased %>
  <%= form.input :quantity_used %>
  <%= form.submit class: "govuk-button" %>
<% end %>

app/views/software_instances/_software_instance.html.erb
<tr class="govuk-table__row" id="<%= dom_id software_instance %>">
  <td  class="govuk-table__cell"><%= software_instance.name %></td>
  <td class="govuk-table__cell"><%= software_instance.organisation.name %></td>
  <td class="govuk-table__cell"><%= software_instance.product %></td>
  <td class="govuk-table__cell"><%= software_instance.packages %></td>
  <td class="govuk-table__cell"><%= software_instance.provider %></td>
  <td class="govuk-table__cell"><%= software_instance.status %></td>
  <td class="govuk-table__cell"><%= govuk_link_to "Show", software_instance %></td>
</tr>

app/views/software_instances/edit.html.erb
<h1 class="govuk-heading-l">Editing software instance</h1>

<%= render "form", software_instance: @software_instance %>

<br>

<div>
  <%= govuk_link_to "Show this software instance", @software_instance %> |
  <%= govuk_link_to "Back to software instances", organisation_software_instances_path(@organisation) %>
</div>

app/views/software_instances/index.html.erb
<h1><%= @organisation.name.capitalize %></h1>

<h2>Software</h2>

<% if @organisation.software_instances.present? %>
  <table class="govuk-table" id="software_instances">
    <thead class="govuk-table__head">
      <tr class="govuk-table__row"">
        <th class="govuk-table__header">Name</th>
        <th class="govuk-table__header">Organisation</th>
        <th class="govuk-table__header">Product</th>
        <th class="govuk-table__header">Packages</th>
        <th class="govuk-table__header">Provider</th>
        <th class="govuk-table__header">Status</th>
        <th class="govuk-table__header"></th>
      </tr>
    </thead>
    <tbody class="govuk-table__body">
      <% @software_instances.each do |software_instance| %>
        <%= render software_instance %>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Software not found for this organisation</p>
<% end %>

<%= govuk_link_to(
      "Edit this organisation",
      edit_organisation_path(@organisation)
    ) if policy(@organisation).edit? %>

<%= button_to(
      "Destroy this organisation",
      @organisation,
      method: :delete,
      class: "govuk-button govuk-button--warning govuk-!-margin-top-5",
      data: { module: "govuk-button" }
    ) if policy(@organisation).destroy? %>

<%= govuk_link_to(
      "New software instance",
      new_organisation_software_instance_path(@organisation)
    ) if policy(:software_instance).new? %>

<%= govuk_link_to "Back to organisations", root_path %>

app/views/software_instances/new.html.erb
<h1 class="govuk-heading-l">New software instance</h1>

<%= render "form", software_instance: [@organisation, @software_instance] %>

<br>

<div>
  <%= govuk_link_to "Back to list", organisation_software_instances_path(@organisation) %>
</div>

app/views/software_instances/show.html.erb
<div id="<%= dom_id @software_instance %>">
  <p>
    <strong>Name:</strong>
    <%= @software_instance.name %>
  </p>

  <p>
    <strong>Organisation:</strong>
    <%= @software_instance.organisation.name %>
  </p>

  <p>
    <strong>Organisation group:</strong>
    <%= @software_instance.organisation_group %>
  </p>

  <p>
    <strong>Team:</strong>
    <%= @software_instance.team %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= @software_instance.owner %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= @software_instance.product %>
  </p>

  <p>
    <strong>Packages:</strong>
    <%= @software_instance.packages %>
  </p>

  <p>
    <strong>Provider:</strong>
    <%= @software_instance.provider %>
  </p>

  <p>
    <strong>Provider contact:</strong>
    <%= @software_instance.provider_contact %>
  </p>

  <p>
    <strong>Version:</strong>
    <%= @software_instance.version %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @software_instance.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @software_instance.status %>
  </p>

  <p>
    <strong>Internal:</strong>
    <%= @software_instance.internal ? 'Yes' : 'No' %>
  </p>

  <p>
    <strong>License:</strong>
    <%= @software_instance.license %>
  </p>

  <p>
    <strong>Quantity purchased:</strong>
    <%= @software_instance.quantity_purchased %>
  </p>

  <p>
    <strong>Quantity used:</strong>
    <%= @software_instance.quantity_used %>
  </p>

</div>
<div>
  <%= govuk_link_to(
        "Edit",
        edit_software_instance_path(@software_instance)
      ) if policy(@software_instance).edit? %>
  <%= govuk_link_to "Back to list", organisation_software_instances_path(@organisation) %>

  <%= button_to(
        "Destroy",
        @software_instance,
        method: :delete,
        class: "govuk-button govuk-button--warning govuk-!-margin-top-5",
        data: { module: "govuk-button" }
      ) if policy(@software_instance).destroy? %>
</div>